### ISSUE TITLE
Throw a better error than "string indices must be integers"

### ISSUE THREAD

**Issue by nigelbabu** [CentOS/python-cicoclient#19]
Current suspicion is that the string indices error comes from here.
https://github.com/CentOS/python-cicoclient/blob/9ef28be93439d039978b207cff42701e84b69e3f/cicoclient/wrapper.py#L177

**Comment by bowlofeggs** [comment]
I have a traceback that sounds relevant to this ticket:

```
$ cico --debug node get -f value -c hostname -c comment --retry-count 4 --retry-interval 60
Starting new HTTP connection (1): admin.ci.centos.org
Resetting dropped connection: admin.ci.centos.org
string indices must be integers
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cliff/app.py", line 346, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/lib/python2.7/site-packages/cliff/display.py", line 79, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/lib/python2.7/site-packages/cicoclient/utils.py", line 60, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cicoclient/cli.py", line 119, in take_action
    retry_interval=parsed_args.retry_interval)
  File "/usr/lib/python2.7/site-packages/cicoclient/wrapper.py", line 156, in node_get
    for full_host in body['hosts']:
TypeError: string indices must be integers
Traceback (most recent call last):
  File "/usr/bin/cico", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/cicoclient/shell.py", line 71, in main
    return cicocli.run(argv)
  File "/usr/lib/python2.7/site-packages/cliff/app.py", line 226, in run
    result = self.run_subcommand(remainder)
  File "/usr/lib/python2.7/site-packages/cliff/app.py", line 346, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/lib/python2.7/site-packages/cliff/display.py", line 79, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/lib/python2.7/site-packages/cicoclient/utils.py", line 60, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cicoclient/cli.py", line 119, in take_action
    retry_interval=parsed_args.retry_interval)
  File "/usr/lib/python2.7/site-packages/cicoclient/wrapper.py", line 156, in node_get
    for full_host in body['hosts']:
TypeError: string indices must be integers
```

**Comment by evgeni** [comment]
This should be fixed by https://github.com/CentOS/python-cicoclient/pull/26
